version: '3.8'
services:
  gateway:
    build: ./gateway
    image: gateway_image:v1.1.23
    container_name: gateway
    ports:
      - "8080:8080"
    depends_on:
      - server
    environment:
      - SHAREIT_SERVER_URL=http://server:9090
#      - TZ=Europe/Moscow

  server:
    build: ./server
    image: server_image:v1.1.23
    container_name: server
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - DB_NAME=shareit
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - DB_HOST=db
      - DB_PORT=5432
#      - TZ=Europe/Moscow

  db:
    image: postgres:15.1-alpine
    container_name: db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root